FROM python:3.6

WORKDIR /srv/test-proj

#COPY Pipfile ./
#COPY Pipfile.lock ./
#RUN pip install --no-cache-dir pipenv
#RUN pipenv install --system --dev

COPY pyproject.toml ./
COPY poetry.lock ./
RUN pip install --no-cache-dir poetry
RUN poetry config settings.virtualenvs.create false
RUN poetry install

COPY . /srv/test-proj
