version: '3'

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile.dev
      args:
        - PROJECT_DIR=${PROJECT_DIR}
    volumes:
      - ..:${PROJECT_DIR}
    command: "flask run --host=0.0.0.0"
    ports:
      - "5000:5000"
    env_file:
      - dev.env